using WpfApp1;
using System;

namespace DataManagementCom
{
    internal class Program
    {
        static void Main(string[] args)
        {
            ComputerData db = new ComputerData();

            using (db)
            {
                //Computers 
                Computer c1 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c2 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c3 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c4 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c5 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c6 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c7 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c8 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c9 = new Computer  {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c10 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c11 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c12 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c13 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c14 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c15 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c16 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c17 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c18 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c19 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c20 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c21 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c22 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c23 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c24 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c25 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c26 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c27 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c28 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c29 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c30 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c31 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c32 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c33 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c34 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c35 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c36 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c37 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c38 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c39 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c40 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c41 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c42 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c43 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c44 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c45 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c46 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c47 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c48 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c49 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c50 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c51 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c52 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c53 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c54 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c55 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c56 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c57 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c58 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c59 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c60 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c61 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c62 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c63 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c64 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c65 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c66 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c67 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c68 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c69 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c70 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c71 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c72 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c73 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c74 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c75 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c76 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c77 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c78 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c79 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c80 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c81 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c82 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c83 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c84 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c85 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c86 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c87 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c88 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c89 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c90 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c91 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c92 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c93 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c94 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c95 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c96 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c97 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c98 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c99 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c100 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c101 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c102 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c103 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c104 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c105 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c106 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c107 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};
                Computer c108 = new Computer {SoftwareInstalled = "Adobe Photoshop, Microsoft Office, Unity Hub, Visual Studio"};

                //Labs 
                Computer_Lab cl1 = new Computer_Lab()   {Location = "B2307", IsAvailable = false};
                Computer_Lab cl2 = new Computer_Lab()   {Location = "B2308", IsAvailable = true};
                Computer_Lab cl3 = new Computer_Lab()   {Location = "B2309", IsAvailable = false};
                Computer_Lab cl4 = new Computer_Lab()   {Location = "A2329", IsAvailable = true};
                Computer_Lab cl5 = new Computer_Lab()   {Location = "A2324", IsAvailable = false};
                Computer_Lab cl6 = new Computer_Lab()   {Location = "A2326", IsAvailable = true};
                Computer_Lab cl7 = new Computer_Lab()   {Location = "C2246", IsAvailable = false};
                Computer_Lab cl8 = new Computer_Lab()   {Location = "C2244", IsAvailable = true};
                Computer_Lab cl9 = new Computer_Lab()   {Location = "C2248", IsAvailable = false};
                Computer_Lab cl10 = new Computer_Lab()  {Location = "B2448", IsAvailable = false};
                Computer_Lab cl11 = new Computer_Lab()  {Location = "B2444", IsAvailable = true};
                Computer_Lab cl12 = new Computer_Lab()  {Location = "B2445", IsAvailable = false};
                Computer_Lab cl13 = new Computer_Lab()  {Location = "A2642", IsAvailable = true};
                Computer_Lab cl14 = new Computer_Lab()  {Location = "A2643", IsAvailable = false};
                Computer_Lab cl15 = new Computer_Lab()  {Location = "A2645", IsAvailable = true};
                Computer_Lab cl16 = new Computer_Lab()  {Location = "C2642", IsAvailable = false};
                Computer_Lab cl17 = new Computer_Lab()  {Location = "C2643", IsAvailable = true};
                Computer_Lab cl18 = new Computer_Lab()  {Location = "C2644", IsAvailable = true};
                Computer_Lab cl19 = new Computer_Lab()  {Location = "B2954", IsAvailable = false};
                Computer_Lab cl20 = new Computer_Lab()  {Location = "B2955", IsAvailable = true};
                Computer_Lab cl21 = new Computer_Lab()  {Location = "B2956", IsAvailable = false};
                Computer_Lab cl22 = new Computer_Lab()  {Location = "A2193", IsAvailable = true};
                Computer_Lab cl23 = new Computer_Lab()  {Location = "A2194", IsAvailable = false};
                Computer_Lab cl24 = new Computer_Lab()  {Location = "A2195", IsAvailable = true};
                Computer_Lab cl25 = new Computer_Lab()  {Location = "C2154", IsAvailable = false};
                Computer_Lab cl26 = new Computer_Lab()  {Location = "C2156", IsAvailable = true};
                Computer_Lab cl27 = new Computer_Lab()  {Location = "C2157", IsAvailable = false};
                Computer_Lab cl28 = new Computer_Lab()  {Location = "B2236", IsAvailable = false};
                Computer_Lab cl29 = new Computer_Lab()  {Location = "B2238", IsAvailable = true};
                Computer_Lab cl30 = new Computer_Lab()  {Location = "B2239", IsAvailable = false};
                Computer_Lab cl31 = new Computer_Lab()  {Location = "A6578", IsAvailable = true};
                Computer_Lab cl32 = new Computer_Lab()  {Location = "A6579", IsAvailable = false};
                Computer_Lab cl33 = new Computer_Lab()  {Location = "A6574", IsAvailable = true};
                Computer_Lab cl34 = new Computer_Lab()  {Location = "C3465", IsAvailable = false};
                Computer_Lab cl35 = new Computer_Lab()  {Location = "C3466", IsAvailable = true};
                Computer_Lab cl36 = new Computer_Lab()  {Location = "C3467", IsAvailable = true};

                //Exam 
                Exam_Lab el1 = new Exam_Lab  {CourseName = "Games Development Level 7",                     TypeOfExam = "Introduction to Programming 1",            YearGroup = "Year 1 Group A",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 10, 10, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Neil Gannon"};
                Exam_Lab el2 = new Exam_Lab  {CourseName = "Games Development Level 7",                     TypeOfExam = "Mathematics 1",                            YearGroup = "Year 1 Group B",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 11, 12, 00, 00),  LongOfTime = "1 Hours",  TeacherName = "Kieran Hughes"};
                Exam_Lab el3 = new Exam_Lab  {CourseName = "Games Development Level 7",                     TypeOfExam = "Design Thinking",                          YearGroup = "Year 1 Group C",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 12, 09, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Adrian Durcan"};
                Exam_Lab el4 = new Exam_Lab  {CourseName = "Computer Networks and Cyber Security Level 8",  TypeOfExam = "Mathematics 1",                            YearGroup = "Year 1 Group A",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 13, 01, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Kieran Hughes"};
                Exam_Lab el5 = new Exam_Lab  {CourseName = "Computer Networks and Cyber Security Level 8",  TypeOfExam = "Design Thinking",                          YearGroup = "Year 1 Group B",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 14, 02, 00, 00),  LongOfTime = "1 Hours",  TeacherName = "Adrian Durcan"};
                Exam_Lab el6 = new Exam_Lab  {CourseName = "Computer Networks and Cyber Security Level 8",  TypeOfExam = "Introduction to Programming 1",            YearGroup = "Year 1 Group C",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 15, 04, 00, 00),  LongOfTime = "1 Hours",  TeacherName = "Neil Gannon"};
                Exam_Lab el7 = new Exam_Lab  {CourseName = "Electronic and Computer Engineering Level 7",   TypeOfExam = "Mobile Applications Programming",          YearGroup = "Year 1 Group A",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 16, 02, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Keith McManus"};
                Exam_Lab el8 = new Exam_Lab  {CourseName = "Electronic and Computer Engineering Level 7",   TypeOfExam = "Essential Lean Six Sigma and Validation",  YearGroup = "Year 1 Group B",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 17, 03, 00, 00),  LongOfTime = "1 Hours",  TeacherName = "Vivion Kinsella"};
                Exam_Lab el9 = new Exam_Lab  {CourseName = "Electronic and Computer Engineering Level 7",   TypeOfExam = "Embedded System 1",                        YearGroup = "Year 1 Group C",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 18, 05, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Neil Gannon"};
                Exam_Lab el10 = new Exam_Lab {CourseName = "Accounting Level 8",                            TypeOfExam = "Financial Reporting 1",                    YearGroup = "Year 1 Group A",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 19, 02, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Keith McManus"};
                Exam_Lab el11 = new Exam_Lab {CourseName = "Accounting Level 8",                            TypeOfExam = "Business Law For Accountants 1",           YearGroup = "Year 1 Group B",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 20, 03, 00, 00),  LongOfTime = "1 Hours",  TeacherName = "Vivion Kinsella"};
                Exam_Lab el12 = new Exam_Lab {CourseName = "Accounting Level 8",                            TypeOfExam = "Business Mathematics and Statistics 1",    YearGroup = "Year 1 Group C",  Semester = "Semester 1",  DateOfExam = new DateTime(2026, 05, 21, 05, 00, 00),  LongOfTime = "2 Hours",  TeacherName = "Neil Gannon"};


                //Add the Computers into the Labs
                Console.WriteLine(" ---------------------------------------------");
                Console.WriteLine("|     Data Management of the GameLab Hub      |");
                Console.WriteLine("|---------------------------------------------|");
                Console.WriteLine("|---------------------------------------------|");
                Console.WriteLine("| Adding the Computers into the Computer Labs |");
                Console.WriteLine("|---------------------------------------------|");                              
                cl1.Computers.Add(c1);
                cl1.Computers.Add(c2);   
                cl1.Computers.Add(c3);
                cl2.Computers.Add(c4);
                cl2.Computers.Add(c5);
                cl2.Computers.Add(c6);
                cl3.Computers.Add(c7);
                cl3.Computers.Add(c8);
                cl3.Computers.Add(c9);
                cl4.Computers.Add(c10);
                cl4.Computers.Add(c11);
                cl4.Computers.Add(c12);
                cl5.Computers.Add(c13);
                cl5.Computers.Add(c14);
                cl5.Computers.Add(c15);
                cl6.Computers.Add(c16);
                cl6.Computers.Add(c17);
                cl6.Computers.Add(c18);
                cl7.Computers.Add(c19);
                cl7.Computers.Add(c20);
                cl7.Computers.Add(c21);
                cl8.Computers.Add(c22);
                cl8.Computers.Add(c23);
                cl8.Computers.Add(c24);
                cl9.Computers.Add(c25);
                cl9.Computers.Add(c26);
                cl9.Computers.Add(c27);
                cl10.Computers.Add(c28);
                cl10.Computers.Add(c29);
                cl10.Computers.Add(c30);
                cl11.Computers.Add(c31);
                cl11.Computers.Add(c32);
                cl11.Computers.Add(c33);
                cl12.Computers.Add(c34);
                cl12.Computers.Add(c35);
                cl12.Computers.Add(c36);
                cl13.Computers.Add(c37);
                cl13.Computers.Add(c38);
                cl13.Computers.Add(c39);
                cl14.Computers.Add(c40);
                cl14.Computers.Add(c41);
                cl14.Computers.Add(c42);
                cl15.Computers.Add(c43);
                cl15.Computers.Add(c44);
                cl15.Computers.Add(c45);
                cl16.Computers.Add(c46);
                cl16.Computers.Add(c47);
                cl16.Computers.Add(c48);
                cl17.Computers.Add(c49);
                cl17.Computers.Add(c50);
                cl17.Computers.Add(c51);
                cl18.Computers.Add(c52);
                cl18.Computers.Add(c53);
                cl18.Computers.Add(c54);
                cl19.Computers.Add(c56);
                cl19.Computers.Add(c57);
                cl19.Computers.Add(c58);
                cl20.Computers.Add(c59);
                cl20.Computers.Add(c60);
                cl20.Computers.Add(c61);
                cl21.Computers.Add(c62);
                cl21.Computers.Add(c63);
                cl21.Computers.Add(c64);
                cl22.Computers.Add(c65);
                cl22.Computers.Add(c66);
                cl22.Computers.Add(c67);
                cl23.Computers.Add(c68);
                cl23.Computers.Add(c69);
                cl23.Computers.Add(c70);
                cl24.Computers.Add(c71);
                cl24.Computers.Add(c72);
                cl24.Computers.Add(c73);
                cl25.Computers.Add(c74);
                cl25.Computers.Add(c75);
                cl25.Computers.Add(c76);
                cl26.Computers.Add(c77);
                cl26.Computers.Add(c78);
                cl26.Computers.Add(c79);
                cl27.Computers.Add(c80);
                cl27.Computers.Add(c81);
                cl27.Computers.Add(c81);
                cl28.Computers.Add(c82);
                cl28.Computers.Add(c83);
                cl28.Computers.Add(c84);
                cl29.Computers.Add(c85);
                cl29.Computers.Add(c86);
                cl29.Computers.Add(c87);
                cl30.Computers.Add(c88);
                cl30.Computers.Add(c89);
                cl30.Computers.Add(c90);
                cl31.Computers.Add(c91);
                cl31.Computers.Add(c92);
                cl31.Computers.Add(c93);
                cl32.Computers.Add(c94);
                cl32.Computers.Add(c95);
                cl32.Computers.Add(c96);
                cl33.Computers.Add(c97);
                cl33.Computers.Add(c98);
                cl33.Computers.Add(c99);
                cl34.Computers.Add(c100);
                cl34.Computers.Add(c101);
                cl34.Computers.Add(c102);
                cl35.Computers.Add(c103);
                cl35.Computers.Add(c104);
                cl35.Computers.Add(c105);
                cl36.Computers.Add(c106);
                cl36.Computers.Add(c107);
                cl36.Computers.Add(c108);         

                //Add the Labs into the Exam_labs
                Console.WriteLine("|---------------------------------------------|");
                Console.WriteLine("| Adding the Computer Labs into the Exam Labs |");
                Console.WriteLine("|---------------------------------------------|");
                el1.ComputerLabs.Add(cl1);
                el1.ComputerLabs.Add(cl2);
                el1.ComputerLabs.Add(cl3);
                el2.ComputerLabs.Add(cl4);
                el2.ComputerLabs.Add(cl5);
                el2.ComputerLabs.Add(cl6);
                el3.ComputerLabs.Add(cl7);
                el3.ComputerLabs.Add(cl8);
                el3.ComputerLabs.Add(cl9);
                el4.ComputerLabs.Add(cl10);
                el4.ComputerLabs.Add(cl11);
                el4.ComputerLabs.Add(cl12);
                el5.ComputerLabs.Add(cl13);
                el5.ComputerLabs.Add(cl14);
                el5.ComputerLabs.Add(cl15);
                el6.ComputerLabs.Add(cl16);
                el6.ComputerLabs.Add(cl17);
                el6.ComputerLabs.Add(cl18);
                el7.ComputerLabs.Add(cl19);
                el7.ComputerLabs.Add(cl20);
                el7.ComputerLabs.Add(cl21);
                el8.ComputerLabs.Add(cl22);
                el8.ComputerLabs.Add(cl23);
                el8.ComputerLabs.Add(cl24);
                el9.ComputerLabs.Add(cl25);
                el9.ComputerLabs.Add(cl26);
                el9.ComputerLabs.Add(cl27);
                el10.ComputerLabs.Add(cl28);
                el10.ComputerLabs.Add(cl29);
                el10.ComputerLabs.Add(cl30);
                el11.ComputerLabs.Add(cl31);
                el11.ComputerLabs.Add(cl32);
                el11.ComputerLabs.Add(cl33);
                el12.ComputerLabs.Add(cl34);
                el12.ComputerLabs.Add(cl35);
                el12.ComputerLabs.Add(cl36);

                //Add the Labs
                Console.WriteLine("|---------------------------------------------|");
                Console.WriteLine("| Adding the Computer Labs into the Database  |");
                Console.WriteLine("|---------------------------------------------|");
                db.Computer_Labs.Add(cl1);
                db.Computer_Labs.Add(cl2);
                db.Computer_Labs.Add(cl3);
                db.Computer_Labs.Add(cl4);
                db.Computer_Labs.Add(cl5);
                db.Computer_Labs.Add(cl6);
                db.Computer_Labs.Add(cl7);
                db.Computer_Labs.Add(cl8);
                db.Computer_Labs.Add(cl9);

                //Add the Exam_Labs
                Console.WriteLine("|---------------------------------------------|");
                Console.WriteLine("|  Adding the Exam Labs into the Database     |");
                Console.WriteLine("|---------------------------------------------|");
                db.Exam_Labs.Add(el1);
                db.Exam_Labs.Add(el2);
                db.Exam_Labs.Add(el3);
                db.Exam_Labs.Add(el4);
                db.Exam_Labs.Add(el5);
                db.Exam_Labs.Add(el6);
                db.Exam_Labs.Add(el7);
                db.Exam_Labs.Add(el8);
                db.Exam_Labs.Add(el9);
                db.Exam_Labs.Add(el10);
                db.Exam_Labs.Add(el11);
                db.Exam_Labs.Add(el12);


                //Save the changes into the Database
                Console.WriteLine("|---------------------------------------------|");
                Console.WriteLine("|  Saving the new Datas into the Database     |");
                Console.WriteLine(" ---------------------------------------------");
                db.SaveChanges();
            }

        }
    }
}
